# Numpy

## 2D array

In [2]:
a_list = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]

In [3]:
print(a_list)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [4]:
import numpy as np

In [18]:
np_array = np.array( a_list )
print(np_array)
print(type(np_array))
print(np_array[1])
print(np_array[1][1])
print(np_array[1, 1], '\n') #row index, column index

print(np_array[ :, 0])
print(np_array[ :, 2], '\n')

print(np_array[ :2, 0], '\n')

print(np_array[ :2, 1:3], '\n')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
[5 6 7 8]
6
6 

[1 5 9]
[ 3  7 11] 

[1 5] 

[[2 3]
 [6 7]] 



In [20]:
print( np_array.shape )
print( len(np_array) )

(3, 4)
3


In [21]:
print(np_array[ :2, 1:3].shape)

(2, 2)


# 1D array

In [26]:
array_1d = np.array( [1, 5, 7, 9, 71, 14] )

print(array_1d.shape)
print( len(array_1d) )
print( array_1d )

(6,)
6
[ 1  5  7  9 71 14]


In [30]:
list_1d = [1, 5, 7, 9, 71, 14]
print( list_1d * 3 )
print( [number * 3 for number in list_1d] )
print('numpy array')
print(array_1d * 3)
print(array_1d % 2)

[1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14, 1, 5, 7, 9, 71, 14]
[3, 15, 21, 27, 213, 42]
numpy array
[  3  15  21  27 213  42]
[1 1 1 1 1 0]


In [38]:
list_1d = [1, 5, 7, 9, 71, 14]
print( array_1d )
print(list_1d)
list_1d[2:4] = [10,10]
print(list_1d)
# list_1d[2:4] = 50
# print(list_1d)
array_1d[2:4] = [10, 25]
print(array_1d)
array_1d[2:4] = 55
print(array_1d)

[ 1  5 10 25 71 14]
[1, 5, 7, 9, 71, 14]
[1, 5, 10, 10, 71, 14]
[ 1  5 10 25 71 14]
[ 1  5 55 55 71 14]


# 3D array

In [81]:
arr_3d = np.array([
        [ 
            [1, 2, 3], 
            [4, 5, 6]
        ],
        [
            [1, 2, 3],
            [4, 5, 6]
        ]
    ]
)

In [42]:
print(arr_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
print(arr_3d.shape)

(2, 2, 3)


In [50]:
arr_3d[:, :, 2] = 10
print(arr_3d)

[[[ 1  2 10]
  [ 4  5 10]]

 [[ 1  2 10]
  [ 4  5 10]]]


In [82]:
arr_3d[1, 1, :2] = 700
print(arr_3d)

[[[  1   2   3]
  [  4   5   6]]

 [[  1   2   3]
  [700 700   6]]]


# Numpy speed

In [83]:
size = 1_00_000

In [87]:
# %%timeit #Jupyter komanda
py_list = list(range(size))

In [95]:
# %%timeit
np_arr = np.arange(size)

In [89]:
%%timeit
py_list_2 = [ number *2 for number in py_list ]

3.81 ms ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [97]:
%%timeit
np_arr = np.arange(size)
np_arr = np_arr * 1.5

73.7 µs ± 354 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# Numpy reshape

In [99]:
np_array = np.arange(0, 100, 2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [100]:
print(np_array.reshape( (5,10) ))

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [101]:
print(np_array.reshape( (5,2,5) ))

[[[ 0  2  4  6  8]
  [10 12 14 16 18]]

 [[20 22 24 26 28]
  [30 32 34 36 38]]

 [[40 42 44 46 48]
  [50 52 54 56 58]]

 [[60 62 64 66 68]
  [70 72 74 76 78]]

 [[80 82 84 86 88]
  [90 92 94 96 98]]]


In [104]:
print(np_array.reshape( (2,1,-1) )) #-1 palieka tiek, kiek telpa

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


In [105]:
array_3d = np.array( [
    [ [1,2], [4,3], [7,4] ],
    [ [2,2], [4,3], [7,4] ],
    [ [3,2], [4,3], [7,4] ],
    [ [4,2], [4,3], [7,4] ],
]
)

In [107]:
print(array_3d.shape)

(4, 3, 2)


In [108]:
np.mean( array_3d )

3.75

In [111]:
np.mean( array_3d, axis = 0 )

array([[2.5, 2. ],
       [4. , 3. ],
       [7. , 4. ]])

In [115]:
np_array = np.arange(0,20).reshape( (5,4) )
print(np_array)
print(np.mean(np_array, axis = 1))
print(np.mean(np_array, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 1.5  5.5  9.5 13.5 17.5]
[ 8.  9. 10. 11.]


In [116]:
np_array = np.arange(0,20).reshape( (5,4) )
print (np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [117]:
print('Column mean',  np.mean( np_array, axis=0 ) )
print('Row mean', np.mean( np_array, axis=1 ) )

Column mean [ 8.  9. 10. 11.]
Row mean [ 1.5  5.5  9.5 13.5 17.5]


In [120]:
np_array = np.arange(0,20).reshape( (5,4) )
print(np_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [121]:
np.std(np_array)

5.766281297335398

In [123]:
print('Column std', np.std(np_array, axis = 0))
print('Row std', np.std(np_array, axis = 1))

Column std [5.65685425 5.65685425 5.65685425 5.65685425]
Row std [1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]


In [124]:
print('Column sum', np.sum(np_array, axis = 0))
print('Row sum', np.sum(np_array, axis = 1))

Column sum [40 45 50 55]
Row sum [ 6 22 38 54 70]


In [128]:
print(np_array.shape)
print(np_array.T)
print(np_array.T.shape)

(5, 4)
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
(4, 5)


# Numpy comparison

In [129]:
rand_array = np.random.randint(7, 50, 100)
print( rand_array )

[26 10 35 22 17 11 40 43 43 13 33 12 38 19 26 34 41 24 25 23 36 33 25 15
 43 48 29 10 45 12 36 17 33 11 31 29 36 38 41 33 12 19 24 38 17  9 42 23
 49 38 26 25 44 18 23 39 26 10 29 27 38 27 43 28 40 31 27 34 42 25 11  7
 34 37 10  7 40 24 36 34 47 19 39  9 35 44 25 15 33 33 37  8 44 19 36 17
 43 19 38 42]


In [130]:
rand_array [ rand_array > 18 ]

array([26, 35, 22, 40, 43, 43, 33, 38, 19, 26, 34, 41, 24, 25, 23, 36, 33,
       25, 43, 48, 29, 45, 36, 33, 31, 29, 36, 38, 41, 33, 19, 24, 38, 42,
       23, 49, 38, 26, 25, 44, 23, 39, 26, 29, 27, 38, 27, 43, 28, 40, 31,
       27, 34, 42, 25, 34, 37, 40, 24, 36, 34, 47, 19, 39, 35, 44, 25, 33,
       33, 37, 44, 19, 36, 43, 19, 38, 42])

In [131]:
rand_array [ rand_array > 30 ]

array([35, 40, 43, 43, 33, 38, 34, 41, 36, 33, 43, 48, 45, 36, 33, 31, 36,
       38, 41, 33, 38, 42, 49, 38, 44, 39, 38, 43, 40, 31, 34, 42, 34, 37,
       40, 36, 34, 47, 39, 35, 44, 33, 33, 37, 44, 36, 43, 38, 42])

In [133]:
rand_array > 30 # this is called a mask

array([False, False,  True, False, False, False,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True, False,
       False, False,  True,  True, False, False,  True,  True, False,
       False,  True, False,  True, False,  True, False,  True, False,
        True,  True,  True,  True, False, False, False,  True, False,
       False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False, False, False, False,  True, False,  True,
       False,  True,  True, False,  True,  True, False, False, False,
        True,  True, False, False,  True, False,  True,  True,  True,
       False,  True, False,  True,  True, False, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True])

In [136]:
rand_array [ rand_array % 3 == 0 ]

array([33, 12, 24, 36, 33, 15, 48, 45, 12, 36, 33, 36, 33, 12, 24,  9, 42,
       18, 39, 27, 27, 27, 42, 24, 36, 39,  9, 15, 33, 33, 36, 42])

In [137]:
print(rand_array)


[26 10 35 22 17 11 40 43 43 13 33 12 38 19 26 34 41 24 25 23 36 33 25 15
 43 48 29 10 45 12 36 17 33 11 31 29 36 38 41 33 12 19 24 38 17  9 42 23
 49 38 26 25 44 18 23 39 26 10 29 27 38 27 43 28 40 31 27 34 42 25 11  7
 34 37 10  7 40 24 36 34 47 19 39  9 35 44 25 15 33 33 37  8 44 19 36 17
 43 19 38 42]


In [141]:
print(rand_array[ [0,0,0]])
print(rand_array[ [0,21,-1, -2]])

[26 26 26]
[26 33 42 38]


# Pandas

In [142]:
import pandas as pd

In [143]:
df = pd.DataFrame(
    [ ['Jan',58,42,74,22,2.05],
    ['Feb',61,45,78,26,3.02],
    ['Mar',65,48,84,25,2.34],
    ['Apr',67,50,92,28,1.02],
    ['May',71,53,98,35,0.48],
    ['Jun',75,56,107,41,0.11],
    ['Jul',77,58,105,44,0.0],
    ['Aug',77,59,102,43,0.03],
    ['Sep',77,57,103,40,0.17],
    ['Oct',73,54,96,34,0.81],
    ['Nov',64,48,84,30,1.7],
    ['Dec',58,None,None,21,2.56],
    ['Dec',58,42,73,21,2.56] ],
    columns = ['month','avg_high','avg_low','record_high','record_low','avg_precipitation'])

In [144]:
df

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
1    Feb        61     45.0         78.0          26               3.02
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [145]:
df.info() # object - string in Pandas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   month              13 non-null     object 
 1   avg_high           13 non-null     int64  
 2   avg_low            12 non-null     float64
 3   record_high        12 non-null     float64
 4   record_low         13 non-null     int64  
 5   avg_precipitation  13 non-null     float64
dtypes: float64(3), int64(2), object(1)
memory usage: 752.0+ bytes


In [147]:
df.describe()

avg_high    avg_low  record_high  record_low  avg_precipitation
count  13.000000  12.000000    12.000000   13.000000          13.000000
mean   67.769231  51.000000    91.333333   31.538462           1.296154
std     7.639305   6.060303    12.323911    8.501131           1.115210
min    58.000000  42.000000    73.000000   21.000000           0.000000
25%    61.000000  47.250000    82.500000   25.000000           0.170000
50%    67.000000  51.500000    94.000000   30.000000           1.020000
75%    75.000000  56.250000   102.250000   40.000000           2.340000
max    77.000000  59.000000   107.000000   44.000000           3.020000

In [148]:
df.head()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34
3   Apr        67     50.0         92.0          28               1.02
4   May        71     53.0         98.0          35               0.48

In [149]:
df.head(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0   Jan        58     42.0         74.0          22               2.05
1   Feb        61     45.0         78.0          26               3.02
2   Mar        65     48.0         84.0          25               2.34

In [150]:
df.tail()

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
9    Oct        73     54.0         96.0          34               0.81
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [151]:
df.tail(3)

month  avg_high  avg_low  record_high  record_low  avg_precipitation
10   Nov        64     48.0         84.0          30               1.70
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [153]:
list(df.columns)

['month',
 'avg_high',
 'avg_low',
 'record_high',
 'record_low',
 'avg_precipitation']

In [154]:
df.sort_values( 'avg_high' )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56
1    Feb        61     45.0         78.0          26               3.02
10   Nov        64     48.0         84.0          30               1.70
2    Mar        65     48.0         84.0          25               2.34
3    Apr        67     50.0         92.0          28               1.02
4    May        71     53.0         98.0          35               0.48
9    Oct        73     54.0         96.0          34               0.81
5    Jun        75     56.0        107.0          41               0.11
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17

In [157]:
df.sort_values( 'avg_high', ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
11   Dec        58      NaN          NaN          21               2.56
12   Dec        58     42.0         73.0          21               2.56

In [160]:
df.sort_values( ['avg_high', 'avg_low'], ascending=False )

month  avg_high  avg_low  record_high  record_low  avg_precipitation
7    Aug        77     59.0        102.0          43               0.03
6    Jul        77     58.0        105.0          44               0.00
8    Sep        77     57.0        103.0          40               0.17
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [163]:
df_2 = df.sort_values( ['avg_high', 'avg_low'], ascending=[False, True] )
df_2

month  avg_high  avg_low  record_high  record_low  avg_precipitation
8    Sep        77     57.0        103.0          40               0.17
6    Jul        77     58.0        105.0          44               0.00
7    Aug        77     59.0        102.0          43               0.03
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70
1    Feb        61     45.0         78.0          26               3.02
0    Jan        58     42.0         74.0          22               2.05
12   Dec        58     42.0         73.0          21               2.56
11   Dec        58      NaN          NaN          21               2.56

In [166]:
print(df_2[ 'record_low' ])
print(type(df_2[ 'record_low' ]))

8     40
6     44
7     43
5     41
9     34
4     35
3     28
2     25
10    30
1     26
0     22
12    21
11    21
Name: record_low, dtype: int64
<class 'pandas.core.series.Series'>


# loc[index]

In [167]:
df_2.loc[ 10 ]

month                 Nov
avg_high               64
avg_low              48.0
record_high          84.0
record_low             30
avg_precipitation     1.7
Name: 10, dtype: object

# iloc[ row number ]

In [169]:
df_2.iloc[ 10 ]

month                 Jan
avg_high               58
avg_low              42.0
record_high          74.0
record_low             22
avg_precipitation    2.05
Name: 0, dtype: object

In [170]:
df_2.loc[5:10]

month  avg_high  avg_low  record_high  record_low  avg_precipitation
5    Jun        75     56.0        107.0          41               0.11
9    Oct        73     54.0         96.0          34               0.81
4    May        71     53.0         98.0          35               0.48
3    Apr        67     50.0         92.0          28               1.02
2    Mar        65     48.0         84.0          25               2.34
10   Nov        64     48.0         84.0          30               1.70

In [172]:
df_2.loc[ [5, 6, 7, 8, 9, 10], ['avg_high', 'record_high'] ] # df.lock[ row indexes, column indexes ]

avg_high  record_high
5         75        107.0
6         77        105.0
7         77        102.0
8         77        103.0
9         73         96.0
10        64         84.0

In [173]:
df_2.loc[ :, ['avg_high', 'record_high'] ]

avg_high  record_high
8         77        103.0
6         77        105.0
7         77        102.0
5         75        107.0
9         73         96.0
4         71         98.0
3         67         92.0
2         65         84.0
10        64         84.0
1         61         78.0
0         58         74.0
12        58         73.0
11        58          NaN

## changing row indexex

In [174]:
df_3 = df_2.set_index('month')
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation
month                                                               
Sep          77     57.0        103.0          40               0.17
Jul          77     58.0        105.0          44               0.00
Aug          77     59.0        102.0          43               0.03
Jun          75     56.0        107.0          41               0.11
Oct          73     54.0         96.0          34               0.81
May          71     53.0         98.0          35               0.48
Apr          67     50.0         92.0          28               1.02
Mar          65     48.0         84.0          25               2.34
Nov          64     48.0         84.0          30               1.70
Feb          61     45.0         78.0          26               3.02
Jan          58     42.0         74.0          22               2.05
Dec          58     42.0         73.0          21               2.56
Dec          58      NaN          NaN          21               2.56

In [176]:
df_3.loc[ 'Sep']

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
Name: Sep, dtype: float64

In [178]:
df_3.loc[[ 'Sep', 'Dec']]

avg_high  avg_low  record_high  record_low  avg_precipitation
month                                                               
Sep          77     57.0        103.0          40               0.17
Dec          58     42.0         73.0          21               2.56
Dec          58      NaN          NaN          21               2.56

In [181]:
# df_3.iloc[ 'Sep' ] # neveiks
df_3.iloc[ 0 ]

avg_high              77.00
avg_low               57.00
record_high          103.00
record_low            40.00
avg_precipitation      0.17
Name: Sep, dtype: float64

In [185]:
df_3 = df_3.dropna()
df_3

avg_high  avg_low  record_high  record_low  avg_precipitation
month                                                               
Sep          77     57.0        103.0          40               0.17
Jul          77     58.0        105.0          44               0.00
Aug          77     59.0        102.0          43               0.03
Jun          75     56.0        107.0          41               0.11
Oct          73     54.0         96.0          34               0.81
May          71     53.0         98.0          35               0.48
Apr          67     50.0         92.0          28               1.02
Mar          65     48.0         84.0          25               2.34
Nov          64     48.0         84.0          30               1.70
Feb          61     45.0         78.0          26               3.02
Jan          58     42.0         74.0          22               2.05
Dec          58     42.0         73.0          21               2.56

In [186]:
df_3.to_csv('weather.csv')